// Initial data for the application
// This will be used as default data if no localStorage data exists

// Change the function to generate a stable output for initial server-rendering
function generateSampleTransactions() {
  const now = new Date()
  // Use stable dates to prevent hydration mismatch
  const dates = [
    now,
    new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2),
    new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5),
    new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7),
    new Date(now.getFullYear(), now.getMonth(), now.getDate() - 10),
    new Date(now.getFullYear(), now.getMonth(), now.getDate() - 12),
    new Date(now.getFullYear(), now.getMonth(), now.getDate() - 15),
    new Date(now.getFullYear(), now.getMonth(), now.getDate() - 20),
    new Date(now.getFullYear(), now.getMonth() - 1, 15),
    new Date(now.getFullYear(), now.getMonth() - 1, 5),
  ]

  const categories = [
    {
      name: "Groceries",
      type: "debit",
      amount: 78.45,
      description: "Whole Foods",
    },
    {
      name: "Restaurants",
      type: "debit",
      amount: 32.5,
      description: "Chipotle",
    },
    {
      name: "Shopping",
      type: "debit",
      amount: 124.99,
      description: "Amazon",
    },
    {
      name: "Entertainment",
      type: "debit",
      amount: 15.99,
      description: "Netflix",
    },
    {
      name: "Transportation",
      type: "debit",
      amount: 45.67,
      description: "Gas Station",
    },
    {
      name: "Utilities",
      type: "debit",
      amount: 85.33,
      description: "Electric Bill",
    },
    {
      name: "Healthcare",
      type: "debit",
      amount: 25.0,
      description: "Pharmacy",
    },
    {
      name: "Income",
      type: "credit",
      amount: 2500.0,
      description: "Salary Deposit",
    },
    {
      name: "Transfer",
      type: "debit",
      amount: 300.0,
      description: "Transfer to Savings",
    },
    {
      name: "Income",
      type: "credit",
      amount: 750.0,
      description: "Freelance Payment",
    },
  ]

  const transactions = []
  const accountIds = ["acc1", "acc2", "acc3", "acc4"]

  // Generate deterministic transactions instead of random ones
  for (let i = 0; i < 10; i++) {
    const category = categories[i]
    const accountId = accountIds[i % 4]
    const date = dates[i].toISOString()

    transactions.push({
      id: `sample-t${i + 1}`,
      accountId,
      type: category.type,
      description: category.description,
      category: category.name,
      amount: category.amount,
      date,
    })
  }

  // Sort transactions by date (newest first)
  return transactions.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
}

// Generate sample transactions
const sampleTransactions = generateSampleTransactions()

export const initialAccountsData = {
  accounts: [
    {
      id: "acc1",
      name: "Everyday Checking",
      number: "**** 1234",
      type: "checking",
      balance: 2543.87,
      available: 2543.87,
      currency: "USD",
      status: "active",
      isDefault: true,
      openDate: "2022-01-15",
      accountHolder: "John Doe",
      accountType: "Individual",
      interestRate: 0.01,
      routingNumber: "074000078",
      branch: "Main Street Financial Center",
      lastStatement: "2025-03-01",
      overdraftLimit: 500.0,
      jointOwners: [],
      features: ["Online Banking", "Mobile Deposits", "Bill Pay", "Zelle Transfers"],
    },
    {
      id: "acc2",
      name: "Premium Savings",
      number: "**** 5678",
      type: "savings",
      balance: 15750.52,
      available: 15750.52,
      currency: "USD",
      status: "active",
      isDefault: false,
      openDate: "2022-01-15",
      accountHolder: "John Doe",
      accountType: "Individual",
      interestRate: 1.25,
      routingNumber: "074000078",
      branch: "Main Street Financial Center",
      lastStatement: "2025-03-01",
      overdraftLimit: 0.0,
      jointOwners: [],
      features: ["Online Banking", "Mobile Deposits", "Bill Pay", "Zelle Transfers"],
    },
    {
      id: "acc3",
      name: "Joint Checking",
      number: "**** 9012",
      type: "checking",
      balance: 4320.18,
      available: 4320.18,
      currency: "USD",
      status: "active",
      isDefault: false,
      openDate: "2022-01-15",
      accountHolder: "John Doe & Jane Doe",
      accountType: "Joint",
      interestRate: 0.01,
      routingNumber: "074000078",
      branch: "Main Street Financial Center",
      lastStatement: "2025-03-01",
      overdraftLimit: 500.0,
      jointOwners: ["Jane Doe"],
      features: ["Online Banking", "Mobile Deposits", "Bill Pay", "Zelle Transfers"],
    },
    {
      id: "acc4",
      name: "Emergency Fund",
      number: "**** 3456",
      type: "savings",
      balance: 8500.0,
      available: 8500.0,
      currency: "USD",
      status: "active",
      isDefault: false,
      openDate: "2022-01-15",
      accountHolder: "John Doe",
      accountType: "Individual",
      interestRate: 1.25,
      routingNumber: "074000078",
      branch: "Main Street Financial Center",
      lastStatement: "2025-03-01",
      overdraftLimit: 0.0,
      jointOwners: [],
      features: ["Online Banking", "Mobile Deposits", "Bill Pay", "Zelle Transfers"],
    },
  ],
  transactions: [
    // Add the sample transactions to the initial data
    ...sampleTransactions,
    // Keep a few specific transactions at the top for consistency
    {
      id: "t1",
      accountId: "acc1",
      type: "debit",
      description: "Grocery Store",
      category: "Shopping",
      amount: 78.45,
      date: new Date().toISOString(), // Today
    },
    {
      id: "t2",
      accountId: "acc1",
      type: "credit",
      description: "Salary Deposit",
      category: "Income",
      amount: 2500.0,
      date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(), // 2 days ago
    },
  ],
}

export const initialSavingsData = {
  accounts: [
    {
      id: "sav1",
      name: "Emergency Fund",
      number: "**** 5678",
      balance: 15750.52,
      interestRate: 1.25,
      lastInterestPaid: "2025-02-15",
      nextInterestDate: "2025-03-15",
      openDate: "2022-01-15",
      currency: "USD",
      status: "active",
    },
    {
      id: "sav2",
      name: "Vacation Fund",
      number: "**** 3456",
      balance: 8500.0,
      interestRate: 1.5,
      lastInterestPaid: "2025-02-15",
      nextInterestDate: "2025-03-15",
      openDate: "2023-05-10",
      currency: "USD",
      status: "active",
    },
    {
      id: "sav3",
      name: "Home Down Payment",
      number: "**** 7890",
      balance: 32450.75,
      interestRate: 1.75,
      lastInterestPaid: "2025-02-15",
      nextInterestDate: "2025-03-15",
      openDate: "2022-08-22",
      currency: "USD",
      status: "active",
    },
  ],
  goals: [
    {
      id: "goal1",
      name: "Emergency Fund",
      targetAmount: 25000,
      currentAmount: 15750.52,
      targetDate: "2025-12-31",
      accountId: "sav1",
      color: "blue",
      autoTransfer: {
        enabled: true,
        amount: 500,
        frequency: "monthly",
        nextDate: "2025-04-01",
      },
    },
    {
      id: "goal2",
      name: "Summer Vacation",
      targetAmount: 10000,
      currentAmount: 8500,
      targetDate: "2025-06-15",
      accountId: "sav2",
      color: "green",
      autoTransfer: {
        enabled: true,
        amount: 300,
        frequency: "monthly",
        nextDate: "2025-04-01",
      },
    },
    {
      id: "goal3",
      name: "Home Down Payment",
      targetAmount: 50000,
      currentAmount: 32450.75,
      targetDate: "2026-09-30",
      accountId: "sav3",
      color: "purple",
      autoTransfer: {
        enabled: true,
        amount: 1000,
        frequency: "monthly",
        nextDate: "2025-04-01",
      },
    },
  ],
  transactions: [
    {
      id: "st1",
      accountId: "sav1",
      type: "deposit",
      amount: 500,
      date: "2025-03-01T10:30:00",
      description: "Monthly Savings Transfer",
      category: "Automatic Transfer",
    },
    {
      id: "st2",
      accountId: "sav1",
      type: "interest",
      amount: 16.25,
      date: "2025-02-15T00:00:00",
      description: "Interest Payment",
      category: "Interest",
    },
    {
      id: "st3",
      accountId: "sav2",
      type: "deposit",
      amount: 300,
      date: "2025-03-01T10:30:00",
      description: "Monthly Savings Transfer",
      category: "Automatic Transfer",
    },
    {
      id: "st4",
      accountId: "sav2",
      type: "interest",
      amount: 10.52,
      date: "2025-02-15T00:00:00",
      description: "Interest Payment",
      category: "Interest",
    },
    {
      id: "st5",
      accountId: "sav3",
      type: "deposit",
      amount: 1000,
      date: "2025-03-01T10:30:00",
      description: "Monthly Savings Transfer",
      category: "Automatic Transfer",
    },
    {
      id: "st6",
      accountId: "sav3",
      type: "interest",
      amount: 47.25,
      date: "2025-02-15T00:00:00",
      description: "Interest Payment",
      category: "Interest",
    },
  ],
}

export const initialInvestmentsData = {
  accounts: [
    {
      id: "inv1",
      name: "Retirement Portfolio",
      number: "**** 7654",
      balance: 125750.32,
      initialInvestment: 75000,
      returnRate: 8.5,
      openDate: "2020-05-15",
      currency: "USD",
      status: "active",
      type: "401k",
    },
    {
      id: "inv2",
      name: "Stock Portfolio",
      number: "**** 9876",
      balance: 45320.18,
      initialInvestment: 30000,
      returnRate: 12.3,
      openDate: "2021-02-10",
      currency: "USD",
      status: "active",
      type: "brokerage",
    },
  ],
  holdings: [
    {
      id: "hold1",
      accountId: "inv1",
      symbol: "VTI",
      name: "Vanguard Total Stock Market ETF",
      shares: 150,
      purchasePrice: 180.25,
      currentPrice: 245.75,
      sector: "ETF",
      allocation: 45,
    },
    {
      id: "hold2",
      accountId: "inv1",
      symbol: "VXUS",
      name: "Vanguard Total International Stock ETF",
      shares: 120,
      purchasePrice: 52.3,
      currentPrice: 58.45,
      sector: "ETF",
      allocation: 25,
    },
    {
      id: "hold3",
      accountId: "inv1",
      symbol: "BND",
      name: "Vanguard Total Bond Market ETF",
      shares: 200,
      purchasePrice: 82.15,
      currentPrice: 79.3,
      sector: "ETF",
      allocation: 30,
    },
    {
      id: "hold4",
      accountId: "inv2",
      symbol: "AAPL",
      name: "Apple Inc.",
      shares: 25,
      purchasePrice: 145.3,
      currentPrice: 175.45,
      sector: "Technology",
      allocation: 20,
    },
    {
      id: "hold5",
      accountId: "inv2",
      symbol: "MSFT",
      name: "Microsoft Corporation",
      shares: 15,
      purchasePrice: 220.45,
      currentPrice: 315.75,
      sector: "Technology",
      allocation: 25,
    },
    {
      id: "hold6",
      accountId: "inv2",
      symbol: "AMZN",
      name: "Amazon.com Inc.",
      shares: 10,
      purchasePrice: 3100.25,
      currentPrice: 3450.3,
      sector: "Consumer Cyclical",
      allocation: 30,
    },
    {
      id: "hold7",
      accountId: "inv2",
      symbol: "GOOGL",
      name: "Alphabet Inc.",
      shares: 8,
      purchasePrice: 2450.75,
      currentPrice: 2750.25,
      sector: "Communication Services",
      allocation: 25,
    },
  ],
  transactions: [
    {
      id: "it1",
      accountId: "inv1",
      type: "buy",
      symbol: "VTI",
      shares: 50,
      price: 195.45,
      amount: 9772.5,
      date: "2024-12-15T10:30:00",
      description: "Buy VTI",
    },
    {
      id: "it2",
      accountId: "inv1",
      type: "buy",
      symbol: "VXUS",
      shares: 75,
      price: 54.25,
      amount: 4068.75,
      date: "2024-12-15T10:35:00",
      description: "Buy VXUS",
    },
    {
      id: "it3",
      accountId: "inv2",
      type: "buy",
      symbol: "AAPL",
      shares: 10,
      price: 150.25,
      amount: 1502.5,
      date: "2025-01-10T14:20:00",
      description: "Buy AAPL",
    },
    {
      id: "it4",
      accountId: "inv2",
      type: "sell",
      symbol: "MSFT",
      shares: 5,
      price: 310.5,
      amount: 1552.5,
      date: "2025-02-05T11:45:00",
      description: "Sell MSFT",
    },
    {
      id: "it5",
      accountId: "inv1",
      type: "dividend",
      symbol: "VTI",
      shares: 0,
      price: 0,
      amount: 125.75,
      date: "2025-03-01T00:00:00",
      description: "VTI Dividend",
    },
  ],
}

// Add initial profile data
export const initialProfileData = {
  firstName: "John",
  lastName: "Doe",
  email: "john.doe@example.com",
  phone: "(555) 123-4567",
  address: {
    street: "123 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: "12345",
    country: "USA",
  },
  preferences: {
    notifications: {
      email: true,
      sms: false,
      push: true,
    },
    theme: "system",
    language: "en",
    currency: "USD",
    twoFactorAuth: true,
  },
  securityQuestions: [
    {
      question: "What was your first pet's name?",
      answer: "Buddy",
    },
    {
      question: "In what city were you born?",
      answer: "San Francisco",
    },
  ],
}

